apiVersion: 1

datasources:
- name: Home Assistant
  type: influxdb
  access: proxy
  orgId: 1
  url: http://localhost:8086
  password:
  user: root
  database: home_assistant
  isDefault: true
  version: 1
  editable: true

